# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LongHuTianJieShop' do
  pod 'LookinServer', :configurations => ['Debug']
  pod 'AFNetworking', '~> 4.0'
  pod 'JSONModel'
  pod 'SDWebImage', '~> 5.0'
  pod 'MJRefresh'
end
